/**
 * Vercel Serverless Function — Bynder DAM upload proxy
 * Route: /api/bynder (POST)
 */

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  const { bynder_domain, bynder_token, image_url, filename = 'telia-brand-image.png', brand_id } = req.body || {};

  if (!bynder_domain || !bynder_token || !image_url) {
    return res.status(400).json({ error: 'Missing bynder_domain, bynder_token or image_url' });
  }

  const base = bynder_domain.startsWith('http') ? bynder_domain : `https://${bynder_domain}`;

  async function bynderGet(path) {
    const r = await fetch(base + path, {
      headers: { Authorization: `Bearer ${bynder_token}`, 'User-Agent': 'TeliaImageStudio/1.0' },
    });
    return r.json();
  }

  try {
    // 0. Fetch image
    const imgResp = await fetch(image_url, { headers: { 'User-Agent': 'TeliaImageStudio/1.0' } });
    const imgBuffer = Buffer.from(await imgResp.arrayBuffer());

    // 1. Init upload
    const init = await bynderGet('/api/upload/init/');
    const s3Filename = init.s3_filename || '';
    const s3Endpoint = init.s3endpoint || {};
    const targetUrl = s3Endpoint.targeturl || '';
    const multiParams = s3Endpoint.multipart_params || {};

    if (!targetUrl) {
      return res.status(502).json({ error: 'Bynder init did not return upload URL', detail: init });
    }

    // 2. Upload to S3 (multipart form)
    const formData = new FormData();
    for (const [k, v] of Object.entries(multiParams)) {
      formData.append(k, v);
    }
    formData.append('file', new Blob([imgBuffer], { type: 'image/png' }), filename);

    await fetch(targetUrl, { method: 'POST', body: formData });

    // 3. Register upload chunk
    const regBody = new URLSearchParams({
      s3_filename: `${s3Filename}/p1`,
      chunks: '1',
    });
    const regResp = await fetch(base + '/api/v4/upload/', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${bynder_token}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'TeliaImageStudio/1.0',
      },
      body: regBody.toString(),
    });
    const regResult = await regResp.json();
    const importId = regResult.importId || '';
    if (!importId) {
      return res.status(502).json({ error: 'No importId returned', detail: regResult });
    }

    // 4. Poll until done
    for (let i = 0; i < 15; i++) {
      const status = await bynderGet(`/api/v4/upload/${importId}/`);
      if ((status.itemsDone || 0) >= (status.itemsTotal || 1)) break;
      await new Promise(r => setTimeout(r, 2000));
    }

    // 5. Save as media asset
    const saveData = new URLSearchParams({
      importId,
      name: filename.replace('.png', ''),
      description: 'Generated by Telia Image Studio',
    });
    if (brand_id) saveData.append('brandId', brand_id);

    const saveResp = await fetch(base + `/api/v4/media/save/${importId}/`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${bynder_token}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'TeliaImageStudio/1.0',
      },
      body: saveData.toString(),
    });
    const saveResult = await saveResp.json();

    return res.status(200).json({ success: true, mediaid: saveResult.mediaid || '', detail: saveResult });
  } catch (e) {
    return res.status(502).json({ error: e.message });
  }
}
